<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\03.Modules\Audit\EnglishTutor.Audit.Domain\EnglishTutor.Audit.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\03.Modules\Audit\EnglishTutor.Audit.Application\EnglishTutor.Audit.Application.csproj" />
    <ProjectReference Include="..\..\..\..\src\03.Modules\Audit\EnglishTutor.Audit.Contracts\EnglishTutor.Audit.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
