<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\04.BuildingBlocks\EnglishTutor.BuildingBlocks.Presentation\EnglishTutor.BuildingBlocks.Presentation.csproj" />
    <ProjectReference Include="..\EnglishTutor.Feedback.Application\EnglishTutor.Feedback.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Feedback.Contracts\EnglishTutor.Feedback.Contracts.csproj" />
  </ItemGroup>
</Project>
