<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Modules.AI.Application\EnglishTutor.Modules.AI.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Modules.AI.Contracts\EnglishTutor.Modules.AI.Contracts.csproj" />
    <ProjectReference Include="..\EnglishTutor.Modules.AI.Domain\EnglishTutor.Modules.AI.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Infrastructure\EnglishTutor.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Outbox\EnglishTutor.BuildingBlocks.Outbox.csproj" />
  </ItemGroup>
</Project>
