<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Modules.AdminReports.Domain\EnglishTutor.Modules.AdminReports.Domain.csproj" />
    <ProjectReference Include="..\..\Auth\EnglishTutor.Modules.Auth.Contracts\EnglishTutor.Modules.Auth.Contracts.csproj" />
    <ProjectReference Include="..\..\Exercises\EnglishTutor.Modules.Exercises.Contracts\EnglishTutor.Modules.Exercises.Contracts.csproj" />
    <ProjectReference Include="..\..\Speaking\EnglishTutor.Modules.Speaking.Contracts\EnglishTutor.Modules.Speaking.Contracts.csproj" />
    <ProjectReference Include="..\..\Users\EnglishTutor.Modules.Users.Contracts\EnglishTutor.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\..\Vocabulary\EnglishTutor.Modules.Vocabulary.Contracts\EnglishTutor.Modules.Vocabulary.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Application\EnglishTutor.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.EventBus\EnglishTutor.BuildingBlocks.EventBus.csproj" />
  </ItemGroup>
</Project>
