<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Realtime.Application\EnglishTutor.Realtime.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Realtime.Contracts\EnglishTutor.Realtime.Contracts.csproj" />
  </ItemGroup>
</Project>
