// <auto-generated />
using System;
using EnglishTutor.Progress.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishTutor.Progress.Infrastructure.Migrations
{
    [DbContext(typeof(ProgressDbContext))]
    [Migration("20260629035220_InitialProgressLanguageProjection")]
    partial class InitialProgressLanguageProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("progress")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishTutor.BuildingBlocks.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("MessageId", "ConsumerName");

                    b.HasIndex("CompletedAtUtc");

                    b.ToTable("InboxMessages", "progress");
                });

            modelBuilder.Entity("EnglishTutor.Progress.Domain.Aggregates.LearnerLanguageProgress.LearnerLanguageProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CurrentCefrLevel")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("current_cefr_level");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<int>("FeedbackCount")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_count");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LanguagePairId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_pair_id");

                    b.Property<DateTime?>("LastPracticedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_practiced_at_utc");

                    b.Property<int?>("LatestScore")
                        .HasColumnType("integer")
                        .HasColumnName("latest_score");

                    b.Property<string>("NativeLanguageCode")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("native_language_code");

                    b.Property<int>("SessionsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("sessions_completed");

                    b.Property<long>("SpeakingSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("speaking_seconds");

                    b.Property<string>("TargetLanguageCode")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("target_language_code");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LanguagePairId")
                        .IsUnique();

                    b.ToTable("learner_language_progress", "progress");
                });
#pragma warning restore 612, 618
        }
    }
}
