<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Identity.Domain\EnglishTutor.Identity.Domain.csproj" />
    <ProjectReference Include="..\EnglishTutor.Identity.Contracts\EnglishTutor.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Application\EnglishTutor.BuildingBlocks.Application.csproj" />
  </ItemGroup>

</Project>
