<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Audit.Application\EnglishTutor.Audit.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Audit.Contracts\EnglishTutor.Audit.Contracts.csproj" />
  </ItemGroup>
</Project>
