<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Quota.Domain\EnglishTutor.Quota.Domain.csproj" />
    <ProjectReference Include="..\EnglishTutor.Quota.Contracts\EnglishTutor.Quota.Contracts.csproj" />
    <ProjectReference Include="..\..\..\04.BuildingBlocks\EnglishTutor.BuildingBlocks.Application\EnglishTutor.BuildingBlocks.Application.csproj" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
</Project>
