<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Quota.Application\EnglishTutor.Quota.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Quota.Contracts\EnglishTutor.Quota.Contracts.csproj" />
  </ItemGroup>
</Project>
