<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Realtime.Application\EnglishTutor.Realtime.Application.csproj" />
    <ProjectReference Include="..\..\Feedback\EnglishTutor.Feedback.Contracts\EnglishTutor.Feedback.Contracts.csproj" />
    <ProjectReference Include="..\..\..\04.BuildingBlocks\EnglishTutor.BuildingBlocks.Infrastructure\EnglishTutor.BuildingBlocks.Infrastructure.csproj" />
  </ItemGroup>
</Project>
