<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Modules.Progress.Domain\EnglishTutor.Modules.Progress.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Application\EnglishTutor.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.EventBus\EnglishTutor.BuildingBlocks.EventBus.csproj" />
    <ProjectReference Include="..\..\Vocabulary\EnglishTutor.Modules.Vocabulary.Contracts\EnglishTutor.Modules.Vocabulary.Contracts.csproj" />
    <ProjectReference Include="..\..\Speaking\EnglishTutor.Modules.Speaking.Contracts\EnglishTutor.Modules.Speaking.Contracts.csproj" />
    <ProjectReference Include="..\..\Mistakes\EnglishTutor.Modules.Mistakes.Contracts\EnglishTutor.Modules.Mistakes.Contracts.csproj" />
  </ItemGroup>
</Project>
