// <auto-generated />
using System;
using EnglishTutor.Practice.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishTutor.Practice.Infrastructure.Migrations
{
    [DbContext(typeof(PracticeDbContext))]
    [Migration("20260629035041_AddPracticeLanguageSnapshot")]
    partial class AddPracticeLanguageSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("practice")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishTutor.BuildingBlocks.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CausationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("LockId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("LockedUntilUtc");

                    b.HasIndex("PublishedAtUtc");

                    b.HasIndex("Status", "NextAttemptAtUtc", "OccurredAtUtc");

                    b.ToTable("integration_outbox_messages", "practice");
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeScenarioReadModel.PracticeScenarioReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("LearnerFacingInstructions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("learner_facing_instructions");

                    b.Property<string>("ModeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mode_code");

                    b.Property<Guid>("ModeDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("mode_definition_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("topic_code");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid")
                        .HasColumnName("topic_id");

                    b.Property<string>("TopicTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("topic_title");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("scenario_read_models", "practice");
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.Entities.SessionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSessionId")
                        .HasDatabaseName("ix_session_events_session_id");

                    b.ToTable("session_events", "practice");
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.Entities.TranscriptMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("PracticeSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("practice_session_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_number");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("PracticeSessionId", "SequenceNumber")
                        .HasDatabaseName("ix_transcript_messages_session_seq");

                    b.ToTable("transcript_messages", "practice");
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.PracticeSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("end_reason");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("QuotaReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("quota_reservation_id");

                    b.Property<Guid>("RouteLeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_lease_id");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_practice_sessions_user_id");

                    b.HasIndex("UserId", "StartedAtUtc")
                        .HasDatabaseName("ix_practice_sessions_user_id_started_at");

                    b.ToTable("practice_sessions", "practice");
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.Entities.SessionEvent", b =>
                {
                    b.HasOne("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.PracticeSession", null)
                        .WithMany("SessionEvents")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.Entities.TranscriptMessage", b =>
                {
                    b.HasOne("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.PracticeSession", null)
                        .WithMany("TranscriptMessages")
                        .HasForeignKey("PracticeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.PracticeSession", b =>
                {
                    b.OwnsOne("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.ValueObjects.PracticeSessionLanguageSnapshot", "LanguageSnapshot", b1 =>
                        {
                            b1.Property<Guid>("PracticeSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExplanationLanguageCode")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("explanation_language_code");

                            b1.Property<Guid>("LanguagePairId")
                                .HasColumnType("uuid")
                                .HasColumnName("language_pair_id");

                            b1.Property<long>("LanguagePairVersion")
                                .HasColumnType("bigint")
                                .HasColumnName("language_pair_version");

                            b1.Property<string>("NativeLanguageCode")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("native_language_code");

                            b1.Property<string>("TargetLanguageCode")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("target_language_code");

                            b1.HasKey("PracticeSessionId");

                            b1.ToTable("practice_sessions", "practice");

                            b1.WithOwner()
                                .HasForeignKey("PracticeSessionId");
                        });

                    b.OwnsOne("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.ValueObjects.PracticeSessionScenarioSnapshot", "ScenarioSnapshot", b1 =>
                        {
                            b1.Property<Guid>("PracticeSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LearnerFacingInstructions")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("learner_facing_instructions");

                            b1.Property<string>("ModeCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("mode_code");

                            b1.Property<Guid>("ModeDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("mode_definition_id");

                            b1.Property<Guid>("ScenarioId")
                                .HasColumnType("uuid")
                                .HasColumnName("scenario_id");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("title");

                            b1.Property<string>("TopicCode")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("topic_code");

                            b1.Property<Guid>("TopicId")
                                .HasColumnType("uuid")
                                .HasColumnName("topic_id");

                            b1.Property<string>("TopicTitle")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("topic_title");

                            b1.HasKey("PracticeSessionId");

                            b1.ToTable("practice_sessions", "practice");

                            b1.WithOwner()
                                .HasForeignKey("PracticeSessionId");
                        });

                    b.Navigation("LanguageSnapshot")
                        .IsRequired();

                    b.Navigation("ScenarioSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishTutor.Practice.Domain.Aggregates.PracticeSession.PracticeSession", b =>
                {
                    b.Navigation("SessionEvents");

                    b.Navigation("TranscriptMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
