<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Modules.Speaking.Application\EnglishTutor.Modules.Speaking.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Modules.Speaking.Contracts\EnglishTutor.Modules.Speaking.Contracts.csproj" />
    <ProjectReference Include="..\EnglishTutor.Modules.Speaking.Domain\EnglishTutor.Modules.Speaking.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Infrastructure\EnglishTutor.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Outbox\EnglishTutor.BuildingBlocks.Outbox.csproj" />
  </ItemGroup>
</Project>
