<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\04.BuildingBlocks\EnglishTutor.BuildingBlocks.Presentation\EnglishTutor.BuildingBlocks.Presentation.csproj" />
    <ProjectReference Include="..\EnglishTutor.Practice.Application\EnglishTutor.Practice.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Practice.Contracts\EnglishTutor.Practice.Contracts.csproj" />
  </ItemGroup>
</Project>
