<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnglishTutor.Modules.Exercises.Contracts\EnglishTutor.Modules.Exercises.Contracts.csproj" />
    <ProjectReference Include="..\EnglishTutor.Modules.Exercises.Domain\EnglishTutor.Modules.Exercises.Domain.csproj" />
    <ProjectReference Include="..\..\AI\EnglishTutor.Modules.AI.Contracts\EnglishTutor.Modules.AI.Contracts.csproj" />
    <ProjectReference Include="..\..\Users\EnglishTutor.Modules.Users.Contracts\EnglishTutor.Modules.Users.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EnglishTutor.BuildingBlocks.Application\EnglishTutor.BuildingBlocks.Application.csproj" />
  </ItemGroup>
</Project>
