<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\04.BuildingBlocks\EnglishTutor.BuildingBlocks.Presentation\EnglishTutor.BuildingBlocks.Presentation.csproj" />
    <ProjectReference Include="..\EnglishTutor.Learning.Application\EnglishTutor.Learning.Application.csproj" />
    <ProjectReference Include="..\EnglishTutor.Learning.Contracts\EnglishTutor.Learning.Contracts.csproj" />
    <ProjectReference Include="..\..\Identity\EnglishTutor.Identity.Contracts\EnglishTutor.Identity.Contracts.csproj" />
  </ItemGroup>
</Project>
