// <auto-generated />
using System;
using EnglishTutor.Modules.Speaking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnglishTutor.Modules.Speaking.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SpeakingDbContext))]
    [Migration("20260518145556_AddAuditAndSoftDelete")]
    partial class AddAuditAndSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("speaking")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnglishTutor.BuildingBlocks.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NextRetryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextRetryAtUtc");

                    b.ToTable("OutboxMessages", "speaking");
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.ConversationPracticeResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationScenarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpeakingSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskCompletionScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ConversationPracticeResults", "speaking");
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Topic")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SpeakingSessions", "speaking");
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingSessionSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AverageFluencyScore")
                        .HasColumnType("integer");

                    b.Property<int>("AverageGrammarScore")
                        .HasColumnType("integer");

                    b.Property<int>("AveragePronunciationScore")
                        .HasColumnType("integer");

                    b.Property<int>("AverageVocabularyScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SpeakingSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StrongPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetLanguageCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("TotalMistakes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTurns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeakPoints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingSessionId")
                        .IsUnique();

                    b.ToTable("SpeakingSessionSummaries", "speaking");
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingTurn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpeakingSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingSessionId", "TurnNumber")
                        .IsUnique();

                    b.ToTable("SpeakingTurns", "speaking");
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingTurnResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("CorrectedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackLanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FluencyScore")
                        .HasColumnType("integer");

                    b.Property<int>("GrammarScore")
                        .HasColumnType("integer");

                    b.Property<string>("NaturalVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<int>("PronunciationScore")
                        .HasColumnType("integer");

                    b.Property<string>("RecognizedText")
                        .HasColumnType("text");

                    b.Property<Guid>("SpeakingTurnId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetLanguageCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("TaskCompletionScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("VocabularyScore")
                        .HasColumnType("integer");

                    b.Property<string>("WordLevelFeedbackJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingTurnId")
                        .IsUnique();

                    b.ToTable("SpeakingTurnResults", "speaking");
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingSession", b =>
                {
                    b.OwnsOne("EnglishTutor.Modules.Speaking.Domain.ValueObjects.LanguageSnapshot", "LanguageSnapshot", b1 =>
                        {
                            b1.Property<Guid>("SpeakingSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExplanationLanguageCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("ExplanationLanguageCodeAtStart");

                            b1.Property<string>("NativeLanguageCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("NativeLanguageCodeAtStart");

                            b1.Property<string>("TargetLanguageCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TargetLanguageCodeAtStart");

                            b1.Property<string>("UiLanguageCode")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("UiLanguageCodeAtStart");

                            b1.Property<string>("UserLevel")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("UserLevelAtStart");

                            b1.HasKey("SpeakingSessionId");

                            b1.ToTable("SpeakingSessions", "speaking");

                            b1.WithOwner()
                                .HasForeignKey("SpeakingSessionId");
                        });

                    b.Navigation("LanguageSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingTurn", b =>
                {
                    b.HasOne("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingSession", null)
                        .WithMany("Turns")
                        .HasForeignKey("SpeakingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EnglishTutor.Modules.Speaking.Domain.Entities.SpeakingSession", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
